# This is my learning Python course

We **are** learning ~~matlab~~ *python* using `jupyter` notebooks.

# Analysing patient data

In [1]:
import numpy as np

In [2]:
np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [3]:
weight_kg = 55
print(weight_kg)

55


In [4]:
print("Weight in pounds:", 2.2 * weight_kg)

Weight in pounds: 121.00000000000001


In [5]:
weight_kg = 57.4
print("Weight in kg:", weight_kg)

Weight in kg: 57.4


In [6]:
weight_lb = 2.2 * weight_kg
print("Weight in pounds:", weight_lb, "and in kg:", weight_kg)

Weight in pounds: 126.28 and in kg: 57.4


In [7]:
weight_kg = 100

In [8]:
print("Weight in pounds:", weight_lb, "and in kg:", weight_kg)

Weight in pounds: 126.28 and in kg: 100


In [9]:
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [10]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [11]:
%whos

Variable    Type       Data/Info
--------------------------------
data        ndarray    60x40: 2400 elems, type `float64`, 19200 bytes
np          module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
weight_kg   int        100
weight_lb   float      126.28


In [12]:
print(type(data))

<class 'numpy.ndarray'>


In [13]:
print(type(weight_kg))

<class 'int'>


In [14]:
print(data.dtype)

float64


In [15]:
print(data.size)

2400


In [16]:
print(data.shape)

(60, 40)


In [17]:
print("My first value in data:", data[0][0])

My first value in data: 0.0


In [18]:
print("My middle value in data:", data[30, 20])

My middle value in data: 13.0


In [19]:
print(data[0:4, 0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]


In [20]:
print(data[5:10, 0:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


In [21]:
small = data[:3, 36:]

In [22]:
print("small is")
print(small)

small is
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
